python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/Builder/Release/1000.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_Builder_Release_1000.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/Builder/FJ.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_Builder_FJ.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/release(builder)/crm.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_release(builder)_crm.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/release(builder)/dname.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_release(builder)_dname.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/release(builder)/rsakey.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_release(builder)_rsakey.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/release(builder)/zconv.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_release(builder)_zconv.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/appack.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_appack.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/Android-GMBot-MALWARE-master/Android-GMBot-MALWARE-master/windows/gozi-isfb/Config.exe > results/Botnet_Android-GMBot-MALWARE-master_Android-GMBot-MALWARE-master_windows_gozi-isfb_Config.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/TL-BOTS-master/TL-BOTS-master/TL.MISC/UNSORTED.Scam/Exploits.exe > results/Botnet_TL-BOTS-master_TL-BOTS-master_TL.MISC_UNSORTED.Scam_Exploits.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Botnet/TL-BOTS-master/TL-BOTS-master/TL.MISC/UNSORTED.Scam/Zekrom_v3_botnet_source.exe > results/Botnet_TL-BOTS-master_TL-BOTS-master_TL.MISC_UNSORTED.Scam_Zekrom_v3_botnet_source.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Injection/Instalog-master/Instalog-master/LogTests/TestData/TestVerInfoApp.exe > results/Injection_Instalog-master_Instalog-master_LogTests_TestData_TestVerInfoApp.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Injection/Instalog-master/Instalog-master/ThirdParty/sqlite-amalgamation/sqlite3.exe > results/Injection_Instalog-master_Instalog-master_ThirdParty_sqlite-amalgamation_sqlite3.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Injection/iot-malware-master/iot-malware-master/busybotnet/libssh-0.7.4/build/examples/exec > results/Injection_iot-malware-master_iot-malware-master_busybotnet_libssh-0.7.4_build_examples_exec.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/0xdarkvortex-MalwareDevelopment-master/0xdarkvortex-MalwareDevelopment-master/prometheus.exe > results/Mixed_0xdarkvortex-MalwareDevelopment-master_0xdarkvortex-MalwareDevelopment-master_prometheus.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/adminpanel/bot_aa/crons/pv.exe > results/Mixed_CarberpBotnet_adminpanel_bot_aa_crons_pv.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/adminpanel/bot_az/cache/str2bin/MakeBinConfig2.exe > results/Mixed_CarberpBotnet_adminpanel_bot_az_cache_str2bin_MakeBinConfig2.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/BC/BackServer.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_BC_BackServer.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/bootkit/BkBuild/BkPack.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_bootkit_BkBuild_BkPack.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/BSS/bss.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_BSS_bss.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/DllLoaderHook/Tools/bin2hex.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_DllLoaderHook_Tools_bin2hex.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/DllLoaderHook1/Tools/bin2hex.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_DllLoaderHook1_Tools_bin2hex.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/DropSploit/src/tools/bin2hex.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_DropSploit_src_tools_bin2hex.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/DropSploit1/src/tools/bin2hex.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_DropSploit1_src_tools_bin2hex.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/FakeDllAutorun/tools/BinToHex.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_FakeDllAutorun_tools_BinToHex.exe.output
python getcfg.py --input C:/Users/mango1/Desktop/sourcecode_datasets/datasets/./Mixed/Carberp Botnet/source - absource/pro/all source/GrabberIE_FF/Tools/bin2hex.exe > results/Mixed_CarberpBotnet_source-absource_pro_allsource_GrabberIE_FF_Tools_bin2hex.exe.output
